config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: {
    sessions:       'users/sessions',
    registrations:  'users/registrations'
  }
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :examples
  resources :chat_rooms
  resources :messages
  resources :reports do
    resources :operations
  end
  resources :posts do
    resources :comments
  end
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < AuthorizeController
  def index
    @chat_rooms = ChatRoom.all
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = 'Chat room added!'
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end

  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end
end

app/views/chat_rooms/_chat_room.html.erb
<li>
  <%= link_to "Enter #{chat_room.title}", chat_room_path(chat_room) %>
</li>

app/views/chat_rooms/index.html.erb
<h1>Chat rooms</h1>

<p class="lead"><%= link_to 'New chat room', new_chat_room_path, class: 'btn btn-primary' %></p>

<ul>
  <%= render @chat_rooms %>
<ul>

app/views/chat_rooms/new.html.erb
<h1>Add chat room</h1>

<%= form_for @chat_room do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
  </div>

  <%= f.submit "Add!", class: 'btn btn-primary' %>
<% end %>

app/views/chat_rooms/show.html.erb
<h1><%= @chat_room.title %></h1>

<div id="messages" data-chat-room="Best Room">
  <%= render @chat_room.messages %>
</div>

<%= form_for @message, remote: true do |f| %>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
    <small class="text-muted">From 2 to 1000 characters</small>
  </div>

  <%= f.submit "Post", class: 'btn btn-primary btn-lg' %>
<% end %>