config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: {
    sessions:       'users/sessions',
    registrations:  'users/registrations'
  }
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :examples
  resources :chat_rooms
  resources :messages
  resources :reports do
    resources :operations
  end
  resources :posts do
    resources :comments
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  belongs_to :user

  paginates_per 10

  def body
    annotation.present? ? annotation.truncate(200) : '' 
  end
end

app/controllers/posts_controller.rb
class PostsController < AuthorizeController
  before_action :find_posts, only: [:index]
  before_action :find_post, only: %i[show edit update]
  before_action :check_permissions, only: %i[edit]

  def index; end

  def new
    @post = Post.new(title: 'Пример заголовка')
  end

  def edit; end

  def show; end

  def update
    if @post.update(post_params)
      flash[:success] = 'Пост обновлен'
      redirect_to action: :show
    else
      flash[:warning] = 'Не удалось обновить пост'
    end
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:success] = 'Пост создан'
      redirect_to action: :index
    else
      flash[:warning] = 'Не удалось сохранить пост'
    end
  end

  private

  def find_posts
    @posts = params[:my] ? current_user.posts.page(params[:page] || 1) : Post.page(params[:page] || 1)
  end

  def find_post
    @post = Post.find(params[:id])
  rescue
    render_404
  end

  def post_params
    update_post_params.require(:post).permit(:title, :annotation, :introduction,
                                             :literature_review, :main_part, :conclusions,
                                             bibliography: [], keywords: [])
  end

  def update_post_params
    rework_params = params
    rework_params[:post][:bibliography] = rework_params[:post][:bibliography].split(' ')
    rework_params[:post][:keywords] = rework_params[:post][:keywords].split(' ')
    rework_params
  end

  def check_permissions
    redirect_to(action: :index) unless current_user.id == @post.user_id
  end
end

app/views/posts/_post.html.erb
<div class="card mt-2">
  <%= hidden_field_tag :post_id, post.id %>
    <div class="d-flex justify-content-end">
      <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
        <%= link_to 'Просмотр', post_path(post), class: 'btn btn-primary'%>
          <% if current_user.id == post.user.id %>
            <button type="button" class="btn btn-danger">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
              </svg>
            </button>
          <% end %>
      </div>
    </div>
  <div class="card-body">
    <h5 class="card-title">
      <%= post.title %>  
    </h5>
    <p class="card-text">
      <%= post.body %>
    </p>
    <%= render 'layouts/statistics/stats', likes_count: 0, views_count: 0, comments_count: post.comments.count, id: post.id %>
    <p class="card-text">
      <small class="text-muted">
        Последнее обновление поста <%= post.updated_at.strftime(('%H:%M:%S %d %B %Y')) %>
      </small>
    </p>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <%= form_for @post do |f| %>
    <div class="row justify-content-md-center">
      <%= f.label :title, 'Заголовок' %>
      <%= f.text_field :title, class: 'form-control mt-2' %>
    </div>
    <br>

    <div class="row">
      <%= f.label :annotation, 'Аннотация' %>
      <%= f.text_area :annotation, class: 'form-control mt-2',  rows: '2' %>
    </div>
    <br>

    <div class="row">
      <%= f.label :keywords, 'Ключевые слова' %>
      <%= f.text_field :keywords, class: 'form-control mt-2' %>
    </div>
    <br>

    <div class="row">
      <%= f.label :introduction, 'Введение' %>
      <%= f.text_area :introduction, class: 'form-control mt-2',  rows: '3' %>
    </div>
    <br>

    <div class="row">
      <%= f.label :literature_review, 'Обзор литературы' %>
      <%= f.text_area :literature_review, class: 'form-control mt-2',  rows: '2' %>
    </div>
    <br>

    <div class="row">
      <%= f.label :main_part, 'Основная часть (методология, результаты)' %>
      <%= f.text_area :main_part, class: 'form-control mt-2',  rows: '6' %>
    </div>

    <div class="row">
      <%= f.label :conclusions, 'Выводы и дальнейшие перспективы исследования',  rows: '3' %>
      <%= f.text_area :conclusions, class: 'form-control mt-2' %>
    </div>
    <br>

    <div class="row ">
      <%= f.label :bibliography, 'Список литературы' %>
      <%= f.text_field :bibliography, class: 'form-control mt-2' %>
    </div>
    <br>
    <div class="row">
      <div class="form-group d-flex justify-content-end">
        <div class="btn-group">
          <%= link_to 'Назад', post_path(@post), class: 'btn btn-primary mt-2'%>
          <%= f.submit 'Сохранить', class: 'btn btn-primary mt-2' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<% if @posts.blank? && params[:my] == 'true' %>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Похоже что вы еще не создали ни одного поста...</h5>
      <p class="card-text">
        Перейдите в <%= link_to 'ленту', posts_path(), class: '', 'aria-current' => "page"%> или <%= link_to 'добавьте новый пост', new_post_path(), class: '', 'aria-current' => "page"%>
      </p>
    </div>
  </div>
<% elsif @posts.present? %>
  <% @posts.each do |post| %>
    <%= render 'posts/post', post: post %>
  <% end %>

  <%= paginate @posts %>
<% else %>
  <h2>Лента пуста</h2>
<% end %>

app/views/posts/new.html.erb
<div class="container">
  <%= form_for @post do |f| %>
    <div class="row justify-content-md-center">
      <%= f.label :title, 'Заголовок' %>
      <%= f.text_field :title, class: 'form-control mt-2' %>
    </div>
    <br>

    <div class="row">
      <%= f.label :annotation, 'Аннотация' %>
      <%= f.text_area :annotation, class: 'form-control mt-2',  rows: '2' %>
    </div>
    <br>

    <div class="row">
      <%= f.label :keywords, 'Ключевые слова' %>
      <%= f.text_field :keywords, class: 'form-control mt-2' %>
    </div>
    <br>

    <div class="row">
      <%= f.label :introduction, 'Введение' %>
      <%= f.text_area :introduction, class: 'form-control mt-2',  rows: '3' %>
    </div>
    <br>

    <div class="row">
      <%= f.label :literature_review, 'Обзор литературы' %>
      <%= f.text_area :literature_review, class: 'form-control mt-2',  rows: '2' %>
    </div>
    <br>

    <div class="row">
      <%= f.label :main_part, 'Основная часть (методология, результаты)' %>
      <%= f.text_area :main_part, class: 'form-control mt-2',  rows: '6' %>
    </div>

    <div class="row">
      <%= f.label :conclusions, 'Выводы и дальнейшие перспективы исследования',  rows: '3' %>
      <%= f.text_area :conclusions, class: 'form-control mt-2' %>
    </div>
    <br>

    <div class="row ">
      <%= f.label :bibliography, 'Список литературы' %>
      <%= f.text_field :bibliography, class: 'form-control mt-2' %>
    </div>
    <br>
    <div class="row">
      <div class="form-group d-flex justify-content-end">
        <div class="btn-group">
          <%= f.submit 'Сохранить', class: 'btn btn-primary mt-2' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <h2>
      <%= @post.title %>
    </h2>
  </div>
  <div class="row">
    <p>
      <i>
        <%= @post.annotation %>
      </i>
    </p>
    
    <% if @post.keywords.present? %>
      <p>
      Ключевые слова:
      </p>
      </p>
        <b>
          <%= @post.keywords.join(', ') %>
        </b>
      </p>
    <% end %>
    <br>
    <p>
      <%= @post.introduction %>
    </p>
    <br>
    <p>
      <%= @post.literature_review %>
    </p>
    <p>
      <%= @post.main_part %>
    </p>
    <br>
    <hr>
    <p>
      <%= @post.conclusions %>
    </p>
    <br>
    
    <% if @post.bibliography.present? %>
      <p>
        Список литературы
        <ul>
          <% @post.bibliography.each do |source| %>
            <li>
              <%= source %>
            </li>
          <% end %>
        </ul>
      </p>
    <% end %>
  </div>
  <div class="d-flex justify-content-end">
    <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
      <% if @post.user_id == current_user.id %>
        <%= link_to 'Редактировать', edit_post_path(@post), class: 'btn btn-primary'%>
        <%= link_to 'Удалить', post_path(@post), method: :delete, class: 'btn btn-danger'%>
      <% end %>
    </div>
  </div>
  <div class="d-flex justify-content-end">
    <%= render 'layouts/statistics/stats', likes_count: 0, views_count: 0, comments_count: @post.comments.count, id: @post.id %>
  </div>
  <hr>
  <h5>Комментарии к посту</h5>
  <div class="row comments">
    <div class="" id="collapseComments">
      <ul class="list-group">
        <div data-post-id="<%= @post.id %>">
          <% @post.comments.each do |comment| %>
            <%= render 'comments/comment', comment: comment, post: @post %>
          <% end %>
        </div>
        <li class="list-group-item">
          <div>
            <%= render 'comments/new', post: @post %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>