config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: {
    sessions:       'users/sessions',
    registrations:  'users/registrations'
  }
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :examples
  resources :chat_rooms
  resources :messages
  resources :reports do
    resources :operations
  end
  resources :posts do
    resources :comments
  end
end

app/models/report.rb
# frozen_string_literal: true

class Report < ApplicationRecord
  module Types
    PORTFOLIO_API = 'portfolio_api'
    PORTFOLIO_XLSX = 'portfolio_xlsx'
    def self.all
      [
        PORTFOLIO_API,
        PORTFOLIO_XLSX
      ]
    end
  end

  module Statuses
    CREATED             = 'created'
    RUNNING             = 'running'
    FINISHED_SUCCESS    = 'finished_success'
    FINISHED_WITH_ERROR = 'finished_with_error'

    def self.all
      [
        CREATED,
        RUNNING,
        FINISHED_SUCCESS,
        FINISHED_WITH_ERROR
      ]
    end
  end

  enum report_type: [Types::PORTFOLIO_API, Types::PORTFOLIO_XLSX]
  enum status: [Statuses::CREATED, Statuses::RUNNING, Statuses::FINISHED_SUCCESS, Statuses::FINISHED_WITH_ERROR]

  belongs_to :user
  has_many :positions, dependent: :destroy
  has_many :operations, dependent: :destroy
  has_many :candles, dependent: :destroy

  def interval
    "#{start_date} - #{end_date}"
  end

  def failed?
    status == Statuses::FINISHED_WITH_ERROR
  end

  def start_date_s
    start_date.strftime("%d %B %Y")
  end

  def end_date_s
    end_date.strftime("%d %B %Y ")
  end
end

app/controllers/reports_controller.rb
class ReportsController < AuthorizeController
  before_action :find_reports, only: %i[index]
  before_action :find_report, only: %i[destroy show]

  # rescue_from Reports::Tinkoff::Errors::ApiTokenBlankError, with: :report_failed
  # rescue_from Reports::Tinkoff::Errors::ReportBuildingError, with: :report_failed

  def index; end

  def new
    @report = current_user.reports.new(
      status: Report::Statuses::CREATED,
      start_date: Date.today - 1.year,
      end_date: Date.today
    )
  end

  def create
    if (report = current_user.reports.create(report_params))
      Reports::Tinkoff::Builder.call(report, extra_metadata)

      flash[:success] = 'Начало формирования отчета'
    else
      flash[:warning] = 'Не удалось начать формирование отчета'
    end

    redirect_to action: 'index'
  end

  def show
    @operations = @report.operations
  end

  def destroy
    @report.destroy
  end

  private

  def find_reports
    @reports = current_user.reports.order(created_at: :desc)
  end

  def find_report
    @report = current_user.reports.find(params[:id])
  end

  def report_params
    params.require(:report).permit(:report_type, :status, :start_date, :end_date)
  end

  def extra_metadata
    metadata = {}
    metadata[:broker_report] = params[:report][:broker_report] if params[:report][:broker_report].present?
    metadata
  end

  def report_failed
    redirect_to action: :index
  end
end

app/views/reports/_broker_report_uploader.html.erb
<div id='report_uploader'>
  <div class="alert alert-info" role="alert">
    Для формирования отчета необходимо выгрузить информацию о вашем брокерском счете. Для этого перейдите на сайт Tinkoff, выберите нужный счет и выполните импорт данных.
  </div>
  <div class="input-group mb-3">
    <%= f.label :type, 'Выгрузка из Tinkoff', class: 'col-sm-2 col-form-label' %>
    <div class="custom-file">
      <%= f.file_field :broker_report, class: "custom-file-input" %>
    </div>
  </div>
</div>

app/views/reports/_period.html.erb
<div class="form-group mb-2">
  <%= f.label :start_date, 'Отчет с ', class: 'col-sm-2 col-form-label' %>
  <%= f.date_select :start_date %>
</div>
<div class="form-group mb-2">
  <%= f.label :end_date, 'Отчет по ', class: 'col-sm-2 col-form-label' %>
  <%= f.date_select :end_date %>
</div>

app/views/reports/_report.html.erb
<%
  klass = case report.status
  when Report::Statuses::FINISHED_WITH_ERROR
    'table-danger'
  when Report::Statuses::FINISHED_SUCCESS
    'table-success'
  when Report::Statuses::RUNNING
    'table-active'
  else
    'table-default'
  end
%>

<tr class=<%= klass %>>
  <td>
    <%= t("report.types.#{report.report_type}") %>
  </td>
  <td>
    <%= report.created_at.strftime("%d %B %Y %I:%M%p") %>
  </td>
  <td>
    <%= t("report.statuses.#{report.status}") %>
  </td>
  <td>
    <% case report.status %>
    <% when Report::Statuses::FINISHED_WITH_ERROR %>
      <button type="button" class="btn btn-primary">Повторить</button>
      <%= link_to "Удалить", report, remote: true, method: :delete, class: "btn btn-danger" %>
    <% when Report::Statuses::FINISHED_SUCCESS %>
      <%= link_to "Открыть", report, remote: false, method: :get, class: "btn btn-primary" %>
      <%= link_to "Удалить", report, remote: true, method: :delete, class: "btn btn-danger" %>
    <% else %>
      <%= link_to "Отменить", report, remote: true, method: :delete, class: "btn btn-danger" %>
    <% end %>
  </td>
</tr>

app/views/reports/index.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Отчеты</h5>
    <p class="card-text">
      Найдено <%= @reports.count %> отчетов, сформировать <a href=<%= new_report_path %> class="card-link">новый отчет</a> 
    </p>
  </div>
</div>
<% if @reports.present? %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Тип</th>
        <th scope="col">Дата создания</th>
        <th scope="col">Статус</th>
        <th scope="col">действия</th>
      </tr>
    </thead>
    <tbody>
      <% @reports.each do |report| %>
        <%= render 'report', report: report %>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/reports/new.html.erb
<%= form_for @report, class: 'form-inline' do |f| %>
  <div class="form-group mb-2">
    <div class="input-group mb-3">
      <%= f.label :type, 'Тип отчета', class: 'col-sm-2 col-form-label' %>
      <%= select_tag 'report[report_type]', 
                    options_for_select(report_options),
                    multiple: false, class: 'form-control'
      %>
      <%= f.hidden_field :status %>
    </div>
    <%#= render 'broker_report_uploader', f: f %>
    <%= render '/reports/period', f: f %>

  </div>
  <%= f.submit 'Сформировать', class: 'btn btn-primary' %>
<% end %>

app/views/reports/show.html.erb
<div class="container">
  <div class="row">
    <h1>Аналитика отчета  "<%= t("report.types.#{@report.report_type}") %>"</h1>
  </div>

  <div class="row mt-4">
    <p>
      Отчет по брокерскому счету за период с <%= @report.start_date_s %> по <%= @report.end_date_s %> 
    </p>
  </div>

  <div class="row mt-4">
    <%= render 'reports/operations/index', operations: [] %>
  <div>
</div>