config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: {
    sessions:       'users/sessions',
    registrations:  'users/registrations'
  }
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :examples
  resources :chat_rooms
  resources :messages
  resources :reports do
    resources :operations
  end
  resources :posts do
    resources :comments
  end
end

app/views/layouts/_menu.html.erb
<div class="card" style="width: 18rem;">
  <img class="card-img-top img-thumbnail" src="https://i.pravatar.cc/300" alt="Card image cap" width='100' height='100'>
  <div class="card-body">
    <h5 class="card-title">        
      <%= current_user.name %>
    </h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <%= link_to 'Мои профиль', edit_user_registration_path(my: true), class: 'nav-link active', 'aria-current' => "page"%>
    </li>
    <li class="list-group-item">
      <%= link_to 'Мои посты', posts_path(my: true), class: 'nav-link active', 'aria-current' => "page"%>
    </li>
    <li class="list-group-item">
      <%= link_to 'Мои отчеты', reports_path, class: 'nav-link active', 'aria-current' => "page"%>
    </li>
    <li class="list-group-item">
      <%= link_to 'Лента', posts_path(), class: 'nav-link active', 'aria-current' => "page"%>
    </li>
    <li class="list-group-item">
      <%= link_to 'Чаты', chat_rooms_path, class: 'nav-link active', 'aria-current' => "page"%>
    </li>
  </ul>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between mb-2">
  <div class="container">
    <%= link_to 'Cool app', '/', class: 'navbar-brand'%>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    </div>

    <div class="collapse navbar-collapse d-flex justify-content-end">
    <% if user_signed_in? %>
      <span>
        <%= current_user.name %>
      </span>
      <%= link_to 'Выход', destroy_user_session_path, remote: false, method: :delete, class: 'nav-link active' %>
    <% else %>
      <%= link_to 'Вход', new_user_session_path, class: 'nav-link active' %>
    <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <div class="row justify-content-md-center">
        <div class='col-xl'>
          <% if notice %>
            <div class="alert alert-success" role="alert">
              <%= notice %>
            </div>  
          <% end %>
          
          <% if alert %>
            <div class="alert alert-warning" role="alert">
              <%= alert %>
            </div>     
          <% end %> 

          <% if flash[:success] %>
            <div class="alert alert-success">
              <%= flash[:success] %>
            </div>  
          <% end %>

          <% if flash[:warning] %>
            <div class="alert alert-warning">
              <%= flash[:warning] %>
            </div>  
          <% end %>
          <div class="row">
            <% if current_user.present? %>
              <div class="col-4">
                <%= render 'layouts/menu' %>
              </div>
            <% end %>
            <div class="col-<%= current_user.present? ? '8' : '12' %>">
              <%= yield %>
            </div>
          </div>
      </div>
    </div>
    <div class="alerts">

    </div>
  </body>
</html>